/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'srramas' at '12/23/16 11:58 AM' with Gradle 3.0
 *
 * @author srramas, @date 12/23/16 11:58 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
